name: 🧹 Lint Markdown for Changed Files on PR
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: ⬇️ Checkout repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: ⎔ Setup node
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'

    - name: 📦 Install dependencies
      run: npm ci

    - name: 🔀 Changed files
      uses: tj-actions/changed-files@v47
      id: changed-files
      with:
        files: '**/*.md'
        separator: " "

    - name: 🧹 Markdownlint
      if: steps.changed-files.outputs.any_changed == 'true'
      run: npm run lint:md -- ${ALL_CHANGED_FILES}
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}